const blessingData = {
  
  blessings : [
	{name: "None", hms: [0,0,0], description: ""},
    {name: "Akatosh", hms: [0,0,0], description: "Those blessed by Akatosh are more resistant to fire damage and deal increased elemental damage. Followers who seek their destiny will gain increased magicka regeneration, while his truest champions will gain a boon to magicka, health and stamina."},
    {name: "Arkay", hms: [0,0,0], description: "Those blessed by Arkay are more resilient against physical attacks of undead, can resist a portion of the thu'um, and can endure frost magic more easily. Arkay also grants increased health to worshippers who slay undead. Finally, Arkay rewards great deeds in his name with the ability to absorb and sanctify the evil energies that power undead into enchanted weapons, recharging them whenever a champion slays an undead creature, as well as ignoring a percentage of damage done by incoming hostile spells."},
    {name: "Auriel", hms: [0,25,0], description: "Auriel's blessing confers an increase to magicka and stamina regeneration. Followers of Auriel will also gain the ability to attack with weapons faster the more spells they learn. Finally, Auriel's champions will be granted a flat increase to all physical attack damage and a 50%% increase to all slow time effect durations."},
    {name: "Azura", hms: [0,0,0], description: "Those blessed by Azura can draw slightly more energy from soul gems, cast alteration spells more easily, and can resist poisons more effectively. Followers who trap many souls will be rewarded with self-enchantments being magnified in power, while Azura's champions will be granted a chance to absorb hostile magic."},
    {name: "Boethia", hms: [0,0,0], description: "Those blessed by Boethiah are slightly stealthier and have increased skill with daggers. Boethiah also blesses followers with silenced movement the more sneak attacks they perform. Finally, Boethiah's champions will gain the ability to deal extra sneak attack damage to all targets, even if they would not normally be susceptible to such attacks."},
    {name: "Clavicus Vile", hms: [-15,0,-15], description: "Clavicus Vile's blessing improves the ability of his followers to summon, invoke, or conjure creatures, and will increase any attribute at the expense of the other two attributes. Vile dislikes indecision and punishes followers who do not accept a Bitter Blessing."},
    {name: "Dibella", hms: [0,0,0], description: "Those blessed by Dibella receive the eloquence of grace befitting a warrior of love, allowing them to strike deep into armor and even avoid severe injuries. Dibella also rewards worshippers who persuade great amounts of people with an increasingly greater ability to cast illusion magic. Her most favored followers will be granted otherworldly grace, allowing them to survive falls from any distance unharmed and never get staggered in combat."},
    {name: "Hermaeus Mora", hms: [0,0,0], description: "Followers of Hermaeus Mora will be rewarded with forbidden knowledge, making their spells all the more forceful. This knowledge comes at the cost of increased mental strain. Mora provides those dedicated to lifelong learning the ability to cast spells with greater speed."},
    {name: "Hircine", hms: [0,0,-50], description: "Hircine's blessing improves the skills required to be a hunter, granting greater movement speed and the ability to perceive time slower at will. In addition, werewolves will find their hide stronger with more creatures slain. The burden of the hunt places a great deal of strain on the body of the hunter, and can be only be managed by hunters with the greatest resolve. Those deemed as champions of the hunt will be able to resist magical attacks while in their lycan form."},
    {name: "Julianos", hms: [0,0,0], description: "Those blessed by Julianos are granted additional magicka regeneration and skill with staves in melee combat. Julianos rewards those who progress through learning a magic school with increased magicka, and will strengthen enchanted and infused weapon usage of the mages who prove most worthy of his blessing through talent and titles."},
    {name: "Jyggalag", hms: [0,0,0], description: "Followers of Jyggalag must maintain perfect order, never committing a single crime, serving any other daedra, corrupting their mortality, or wielding the truest source of chaos, magic. In return, Jyggalag bestows incredible endurance upon followers during combat at the expense of swiftness and strength. Jyggalag favors his most determined followers with further protection and damage reflection while blocking or attacking, depending on if you hold one or both of his artifacts."},
    {name: "Kynareth", hms: [0,0,25], description: "Those blessed by Kynareth are granted additional stamina, skill with bows, and can cast wind spells easier. Kynareth also increases the running speed of worshippers who explore and discover many locations. Finally, Kynareth will reward those who perform great deeds in her name with additional stamina regeneration and faster bow draw speed."},
	{name: "Magnus", hms: [0,0,0], description: "All blessed by Magnus are gifted faster magicka regeneration, and less charges used with magic staff enchantments. Those who strive for success in the field of arcane academics will recieve stronger and longer lasting spells while wielding a staff, scaling with College of Winterhold quests completed. Those who prove themselves worthy by acquiring his staff are granted 50 percent stronger staff channeling and staff blessing effects, and a 15 percent decrease to incoming hostile spells."},
    {name: "Malacath", hms: [0,0,0], description: "Malacath's blessing favors the strong, yet weeds out the weak, providing less exhaustion when using devastating strikes, at the cost of being more vulnerable to physical attacks. Followers who prove their mastery over Skyrim's most dangerous beasts will gain mastery in handling melee weapons. Champions shall gain insight into maximizing offensive capability while putting themselves at great risk."},
    {name: "Mara", hms: [0,0,0], description: "Those blessed by Mara find it easier to cast restoration spells, and are slightly protected from magic. In addition, worshippers who cleanse dungeons of various threats will be blessed with life regeneration, and especially dedicated followers will be blessed with extra health. Champions who house the orphaned will have their healing spells empowered."},
    {name: "Mehrunes Dagon", hms: [0,0,0], description: "Mehrunes Dagon blesses followers with cheaper destruction magic, bound weapons dealing elemental damage, and a chance to increasingly absorb incoming spells depending on how much carnage they cause throughout Tamriel. Servants who cause or aid revolutions will be especially favored, but suffer from weakened healing magic. Dagon's destructive urges serve as his greatest strength, but also greatest weakness, manifesting in many followers as an aversion to elemental magic."},
    {name: "Mephala", hms: [0,0,0], description: "Those blessed by Mephala are granted more resistance to potion toxicity and more potent poisons and poison magic. Followers also gain additional uses with each poison the more poisons they brew. Finally, Mephala's most favored servants will gain the ability to reduce many foes' poison resistance by striking them in melee or with marksman, increasing in strength with slower weapons."},
    {name: "Meridia", hms: [0,0,0], description: "Meridia's blessing improves followers' ability to slay undead with the proper weaponry, and makes their restoration spells more effective.  The more undead eradicate, her follows gain increasing resistance to magic. Her unwavering hatred manifests itself to her followers as a double-edged sword, making them suffer greater injuries at the hand of undead."},
    {name: "Molag Bal", hms: [0,0,0], description: "Molag Bal's blessing empowers followers who fight with true hate towards their foes, allowing them to ignore some injuries while attacking at full force. The more people slain by Bal's followers, the stronger their strongest attack becomes. Bal scorns those who do not have the resolve to strike every hit true."},
    {name: "Namira", hms: [0,0,0], description: "Namira blesses followers who embrace their wretchedness, granting great boons to followers wearing the clothes of a beggar, and offering her charity to those that enact her will. Namira forbids opulence, and will retract blessings for use of jewelry other than her own. Her followers are shunned by society and are more susceptible to poisons. Blessed are the sick, for Namira has pity for those plagued with disease."},
    {name: "Nocturnal", hms: [0,0,0], description: "Those blessed by Nocturnal have increased ranged damage and expertise, as well as increased damage and expertise while dual wielding. Followers who complete Thieves Guild missions will gain increased lockpicking expertise and pickpocketing ability, and her Nightingales will deliver critical hits."},
    {name: "Peryite", hms: [0,0,0], description: "Those blessed by Peryite will grow stronger the more diseases they contract, turning symptoms of diseases into boons and spreading those diseases to living targets they attack. They can cook grotesque meals to aid in acquiring disease. In addition, Peryite values the natural order of the world, and will reward the destruction of Dwemer constructs. Peryite carries the burden of pestilence, and quite literally shares this burden with you."},
    {name: "Sanguine", hms: [0,0,0], description: "Sanguine's blessing enhances the merriment of his followers, improving their ability to socialize with others and compete in brawls. They also learn the secrets of cooking skooma from moon sugar. Dedicated individuals will become so good at brawling that they can easily best foes in true fights, especially when under the influence of alcohol or narcotics. Sanguine punishes his followers who participate in any duration of sobriety."},
    {name: "Sheogorath", hms: [0,0,0], description: "Sheogorath's blessing is reliably unreliable. Followers will occasionally find themselves more vulnerable toward enemy attacks. Sheogorath especially favors followers who do mad things, such as fighting with silverware or slaughtering helpless wildlife."},
    {name: "Sithis", hms: [0,0,25], description: "Sithis blesses followers with improved stamina and attacks that ignore a small portion of the enemies armor. Completing Sithis' writs allows his followers absorb health with power attacks and close-range marksman attacks. Sithis will greatly favor those that bring the dark brotherhood to glory with the ability to weaken their foes, and the ability to turn invisible when they slay a foe. Sithis forbids betraying your brothers and sisters or those that serve the Night Mother, and curses his followers with weakened health regeneration."},
    {name: "Stendarr", hms: [0,0,0], description: "Stendarr blesses worshippers with more prowess with swords, with increased effectiveness against vampires and daedra. His blessing also protects against a portion of absorb spells and attacks from daedra. In addition, those who prove their worth by slaying Daedra will be granted increased stamina, and prospective champions who perform great feats in Stendarr's name will gain the ability to stand their ground against even the mightiest of foes and improved penetration with swords."},
	{name: "Syrabane", hms: [0,25,0], description: "Those blessed by Syrabane are granted extra magicka and illusions spells have less of a chance of breaking. Embracing the essence of Skyrim's standing stones allows Syrabane's knowledge to freely flow through you, making spells of all schools easier to cast. Syrabane will offer unparalleled stronger spells to those acknowledged by the very best mages across Tamriel."},
    {name: "Talos", hms: [0,0,0], description: "Those blessed by Talos are granted a bit more stamina regeneration and additional prowess with axes of all kinds. In addition, Talos fortifies the Voice of his few worshippers who are capable of wielding the Thu'um, increasingly so as they slay more dragons. Lastly, Talos rewards those who perform great deeds in his name with greatly increased endurance."},
    {name: "Vaermina", hms: [0,0,0], description: "Vaermina blesses followers with terrible nightmares, the likes of which no battle could match in intensity. Those who manage to sleep suffer less, although can slightly draw more power out of their staves. Followers are able to manipulate a faint aura of hypnosis, controlling the outcomes of a conversation better. Vaermina's followers are able to draw out the full power of magical staves once they begin to understand how magicka's ebb and flow affects the staff. The Skull of Corruption is said to have the ability help control the Dreamstride."},
    {name: "Zenithar", hms: [0,0,0], description: "Those blessed by Zenithar are granted stronger maces and hammers and more carryweight. In addition, Zenithar provides resistance against physical damage according to how much gold his worshippers carry, and will bless those who have rediscovered ancient crafting techniques with increased haggling ability and more efficient augmentations."},
  ]
};

ProcessBlessingData(blessingData);