const gameMechanicsData = {
  
  initialPerks: 3,
  
  oghmaData : {
    perksGiven : 3,
    hmsGiven : [50,100,100]
  },
  
  leveling: {
    base : 75,
    mult : 25,
    hmsGiven : [5,5,5],
	extraHms : [2,0,0],
	extraMR : 0.3,
	maxLevel : 20
  },
  
  derivedAttributes : {
    attribute : ["Magic Resist",
                 "Magicka Regeneration",
                 "Disease Resist",
                 "Poison Resist",
                 "Stamina Regeneration",
                 "Move Speed",
                 "Carry Weight",
                 "Marksman Damage",
                 "One-Handed Damage",
                 "Two-Handed Damage",
                 "Unarmed Damage"],
    isPercent : [true,
                 true,
                 true,
                 true,
                 true,
                 true,
                 false,
                 true,
                 true,
                 true,
                 false],
    prefactor : [1.0,
                8.0,
                4.0,
                4.0,
                8.0,
                0.75,
                4.0,
                4.0,
                4.0,
                4.0,
                4.5],
    threshold : [150,
                 100,
                 100,
                 140,
                 100,
                 125,
                 110,
                 150,
                 150,
                 150,
                 125],
    weight_health : [0,
                     0,
                     0.4,
                     0.6,
                     0,
                     0.2,
                     0.8,
                     0.2,
                     0.5,
                     0.8,
                     0.5],
    weight_magicka : [1,
                      1,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,],
    weight_stamina : [0,
                      0,
                      0.6,
                      0.4,
                      1.0,
                      0.8,
                      0.2,
                      0.8,
                      0.5,
                      0.2,
                      0.5]                     
  }
};

ProcessGameMechanicsData(gameMechanicsData);
